filter_otus_from_otu_table.py -i H-10.biom -o alpha_H-10.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i H-118.biom -o alpha_H-118.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i H-119.biom -o alpha_H-119.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i H-120.biom -o alpha_H-120.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i H-161.biom -o alpha_H-161.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i H-193.biom -o alpha_H-193.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i H-314.biom -o alpha_H-314.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-121.biom -o alpha_O-121.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-122.biom -o alpha_O-122.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-123.biom -o alpha_O-123.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-152.biom -o alpha_O-152.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-39.biom -o alpha_O-39.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-418.biom -o alpha_O-418.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-420.biom -o alpha_O-420.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-434.biom -o alpha_O-434.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i O-445.biom -o alpha_O-445.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i OMC-124.biom -o alpha_OMC-124.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i OMC-125.biom -o alpha_OMC-125.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i OMC-126.biom -o alpha_OMC-126.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i OMC-288.biom -o alpha_OMC-288.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i OMC-446.biom -o alpha_OMC-446.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i OMC-55.biom -o alpha_OMC-55.biom --negate_ids_to_exclude -e alpha_ids.txt
filter_otus_from_otu_table.py -i H-10.biom -o beta_H-10.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i H-118.biom -o beta_H-118.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i H-119.biom -o beta_H-119.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i H-120.biom -o beta_H-120.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i H-161.biom -o beta_H-161.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i H-193.biom -o beta_H-193.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i H-314.biom -o beta_H-314.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-121.biom -o beta_O-121.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-122.biom -o beta_O-122.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-123.biom -o beta_O-123.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-152.biom -o beta_O-152.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-39.biom -o beta_O-39.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-418.biom -o beta_O-418.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-420.biom -o beta_O-420.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-434.biom -o beta_O-434.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i O-445.biom -o beta_O-445.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i OMC-124.biom -o beta_OMC-124.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i OMC-125.biom -o beta_OMC-125.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i OMC-126.biom -o beta_OMC-126.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i OMC-288.biom -o beta_OMC-288.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i OMC-446.biom -o beta_OMC-446.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i OMC-55.biom -o beta_OMC-55.biom --negate_ids_to_exclude -e beta_ids.txt
filter_otus_from_otu_table.py -i H-10.biom -o delta_H-10.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i H-118.biom -o delta_H-118.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i H-119.biom -o delta_H-119.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i H-120.biom -o delta_H-120.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i H-161.biom -o delta_H-161.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i H-193.biom -o delta_H-193.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i H-314.biom -o delta_H-314.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-121.biom -o delta_O-121.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-122.biom -o delta_O-122.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-123.biom -o delta_O-123.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-152.biom -o delta_O-152.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-39.biom -o delta_O-39.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-418.biom -o delta_O-418.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-420.biom -o delta_O-420.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-434.biom -o delta_O-434.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i O-445.biom -o delta_O-445.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i OMC-124.biom -o delta_OMC-124.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i OMC-125.biom -o delta_OMC-125.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i OMC-126.biom -o delta_OMC-126.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i OMC-288.biom -o delta_OMC-288.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i OMC-446.biom -o delta_OMC-446.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i OMC-55.biom -o delta_OMC-55.biom --negate_ids_to_exclude -e delta_ids.txt
filter_otus_from_otu_table.py -i H-10.biom -o gamma_H-10.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i H-118.biom -o gamma_H-118.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i H-119.biom -o gamma_H-119.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i H-120.biom -o gamma_H-120.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i H-161.biom -o gamma_H-161.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i H-193.biom -o gamma_H-193.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i H-314.biom -o gamma_H-314.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-121.biom -o gamma_O-121.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-122.biom -o gamma_O-122.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-123.biom -o gamma_O-123.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-152.biom -o gamma_O-152.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-39.biom -o gamma_O-39.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-418.biom -o gamma_O-418.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-420.biom -o gamma_O-420.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-434.biom -o gamma_O-434.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i O-445.biom -o gamma_O-445.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i OMC-124.biom -o gamma_OMC-124.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i OMC-125.biom -o gamma_OMC-125.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i OMC-126.biom -o gamma_OMC-126.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i OMC-288.biom -o gamma_OMC-288.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i OMC-446.biom -o gamma_OMC-446.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i OMC-55.biom -o gamma_OMC-55.biom --negate_ids_to_exclude -e gamma_ids.txt
filter_otus_from_otu_table.py -i H-10.biom -o no-definido_H-10.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i H-118.biom -o no-definido_H-118.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i H-119.biom -o no-definido_H-119.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i H-120.biom -o no-definido_H-120.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i H-161.biom -o no-definido_H-161.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i H-193.biom -o no-definido_H-193.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i H-314.biom -o no-definido_H-314.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-121.biom -o no-definido_O-121.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-122.biom -o no-definido_O-122.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-123.biom -o no-definido_O-123.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-152.biom -o no-definido_O-152.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-39.biom -o no-definido_O-39.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-418.biom -o no-definido_O-418.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-420.biom -o no-definido_O-420.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-434.biom -o no-definido_O-434.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i O-445.biom -o no-definido_O-445.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i OMC-124.biom -o no-definido_OMC-124.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i OMC-125.biom -o no-definido_OMC-125.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i OMC-126.biom -o no-definido_OMC-126.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i OMC-288.biom -o no-definido_OMC-288.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i OMC-446.biom -o no-definido_OMC-446.biom --negate_ids_to_exclude -e no-definido_ids.txt
filter_otus_from_otu_table.py -i OMC-55.biom -o no-definido_OMC-55.biom --negate_ids_to_exclude -e no-definido_ids.txt
